In [1]:
# imports
import pandas as pd
from datetime import datetime
import matplotlib.pyplot as plt
import seaborn as sns
import os

# regex
import re


import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

In [2]:
df=pd.read_csv('data/reviews.csv')
df

,Unnamed: 0,reviews,stars,date,country
0,0,✅ Trip Verified | Easy check in a T5. Galleri...,8,13th August 2023,United Kingdom
1,1,"Not Verified | Flight delayed by an hour, it ...",2,12th August 2023,United States
2,2,Not Verified | The staff are very rude and not...,2,11th August 2023,United Kingdom
3,3,✅ Trip Verified | Good domestic flight operat...,10,8th August 2023,United Kingdom
4,4,Not Verified | Failed at all basic travel fund...,1,8th August 2023,Canada
...,...,...,...,...,...
365,365,Not Verified | Booked a flight from London to...,1,28th June 2022,United Kingdom
366,366,Not Verified | We left MIA late due to an iss...,1,27th June 2022,United Kingdom
367,367,Not Verified | The flight was delayed over 6 ...,1,27th June 2022,United States
368,368,Not Verified | Terrible experience with Briti...,1,27th June 2022,United Kingdom
369,369,"✅ Trip Verified | BA cancelled my flight, I n...",1,25th June 2022,United Kingdom

In [3]:
# column for verification
df['Verified']=df.reviews.str.contains('Trip Verified')

In [4]:
df

,Unnamed: 0,reviews,stars,date,country,Verified
0,0,✅ Trip Verified | Easy check in a T5. Galleri...,8,13th August 2023,United Kingdom,True
1,1,"Not Verified | Flight delayed by an hour, it ...",2,12th August 2023,United States,False
2,2,Not Verified | The staff are very rude and not...,2,11th August 2023,United Kingdom,False
3,3,✅ Trip Verified | Good domestic flight operat...,10,8th August 2023,United Kingdom,True
4,4,Not Verified | Failed at all basic travel fund...,1,8th August 2023,Canada,False
...,...,...,...,...,...,...
365,365,Not Verified | Booked a flight from London to...,1,28th June 2022,United Kingdom,False
366,366,Not Verified | We left MIA late due to an iss...,1,27th June 2022,United Kingdom,False
367,367,Not Verified | The flight was delayed over 6 ...,1,27th June 2022,United States,False
368,368,Not Verified | Terrible experience with Briti...,1,27th June 2022,United Kingdom,False
369,369,"✅ Trip Verified | BA cancelled my flight, I n...",1,25th June 2022,United Kingdom,True

In [5]:
#for lemmatization of words we will use nltk library
lemma = WordNetLemmatizer()
reviews_data = df.reviews.str.strip("✅ Trip Verified |")
reviews_data

0      Easy check in a T5. Galleries south and North ...
1      Not Verified |  Flight delayed by an hour, it ...
2      Not Verified | The staff are very rude and not...
3      Good domestic flight operated by BA Cityflyer....
4      Not Verified | Failed at all basic travel fund...
                             ...
365    Not Verified |  Booked a flight from London to...
366    Not Verified |  We left MIA late due to an iss...
367    Not Verified |  The flight was delayed over 6 ...
368    Not Verified |  Terrible experience with Briti...
369    BA cancelled my flight, I never got on it, cou...
Name: reviews, Length: 370, dtype: object

In [6]:
#list to collect cleaned data
nltk.download('wordnet')

rev =[]

for x in reviews_data:
    x=re.sub('[^a-zA-Z]',' ',x)
    x=x.lower()
    x=x.split()
    x=[lemma.lemmatize(word) for word in x if word not in set(stopwords.words("english"))]
    x=" ".join(x)
    rev.append(x)

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\ELVIS\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [7]:
df['reviews1']=rev

In [8]:
df.head()

,Unnamed: 0,reviews,stars,date,country,Verified,reviews1
0,0,✅ Trip Verified | Easy check in a T5. Galleri...,8,13th August 2023,United Kingdom,True,easy check gallery south north lounge packed a...
1,1,"Not Verified | Flight delayed by an hour, it ...",2,12th August 2023,United States,False,verified flight delayed hour happens biggie u ...
2,2,Not Verified | The staff are very rude and not...,2,11th August 2023,United Kingdom,False,verified staff rude trained properly exception...
3,3,✅ Trip Verified | Good domestic flight operat...,10,8th August 2023,United Kingdom,True,good domestic flight operated ba cityflyer gro...
4,4,Not Verified | Failed at all basic travel fund...,1,8th August 2023,Canada,False,verified failed basic travel fundamental fligh...

In [9]:
# convert date to datetime format
def clean_date(date_str):
    date_str = re.sub('[^\w\s]', '', date_str)
    date_str = date_str.replace('st', '').replace('nd', '').replace('rd', '').replace('th', '')  # Remove ordinal suffixes
    date_str = date_str.replace(' Augu ', ' August ')
    # date_str = date_str.replace(' July ', ' Jul ')
    # date_str = date_str.replace('June', ' Jun ')
    # date_str = date_str.replace('April', ' Apr ')
    # date_str = date_str.replace('March', ' Mar ')
    # date_str = date_str.replace(' February ', ' Feb ')
    # date_str = date_str.replace('January', ' Jan ')
    # date_str = date_str.replace('December', ' Dec ')
    # date_str = date_str.replace('November', ' Nov ')
    # date_str = date_str.replace('October', ' Oct ')
    # date_str = date_str.replace('September', ' Sep ')
    date_obj = datetime.strptime(date_str, '%d %B %Y')
    return date_obj

df['date'] = df['date'].apply(clean_date)

In [11]:
print(df.date.head())

0   2023-08-13
1   2023-08-12
2   2023-08-11
3   2023-08-08
4   2023-08-08
Name: date, dtype: datetime64[ns]

In [15]:
# check for null values
df.isnull().value_counts()

Unnamed: 0  reviews  stars  date   country  Verified  reviews1
False       False    False  False  False    False     False       370
Name: count, dtype: int64

In [16]:
df.to_csv('data/cleaned-reviews.csv')

OSError: Cannot save file into a non-existent directory: 'dat'